### ISSUE TITLE
Start versioning, tagging and releasing `shared-workflows`

### ISSUE THREAD

**Issue by dsotirakis** [grafana/shared-workflows#133]
We need to start releasing `shared-workflows` so we can then have automatic updates for repos they use them using tools like dependabot. Recommended versioning is semver, so we are aligned with the rest of the products across Grafana Labs.

**Comment by hairyhenderson** [comment]
@dsotirakis FYI I've had success with https://github.com/googleapis/release-please-action for this sort of thing - the only catch is commit messages need to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) convention - LMK if you have questions about it!

**Comment by dsotirakis** [comment]
closing as @iainlane is already working on this
