### ISSUE TITLE
Create github-app for shared workflows

### ISSUE THREAD

**Issue by dsotirakis** [grafana/shared-workflows#138]
We need to create a github app for shared workflows in order to replace the static github tokens

**Comment by ricky-undeadcoders** [comment]
@dsotirakis I'm happy to knock this out. Could you elaborate on the current use cases that static tokens are being used for? I want to make sure I understand the scope of permissions we'll need for this.

**Comment by dsotirakis** [comment]
Still haven't thought if this is worth doing, just put it here so I wouldn't forget to check. So the initial idea was to eliminate things like [this](https://github.com/grafana/shared-workflows/blob/main/.github/workflows/lint-shared-workflows.yaml#L91). The truth is that this is no org or repo secret since this comes straight from the action so we should be good. 
My only concern is whether we could be more consistent, create a github app and make sure that people don't get annoyed about this or explicitly making a comment in that action saying that this is no secret and it comes from the action itself.
Thoughts @iainlane?

**Comment by iainlane** [comment]
You can likely update it to use `${{ github.token }}` if you want? That should be a bit more obvious!

**Comment by ricky-undeadcoders** [comment]
How does this look? https://github.com/grafana/shared-workflows/pull/146
