### ISSUE TITLE
`push-to-dockerhub` action: Only login on push events

### ISSUE THREAD

**Issue by dsotirakis** [grafana/shared-workflows#27]
Based on [this conversation](https://github.com/grafana/shared-workflows/pull/26#discussion_r1444280841), it'll be better if we fail safe in case there's no push event from GitHub, when this action is called. 
The reason we don't do it now is that we first need to make sure that all the images which are not meant to be end-use products use Google Artifact Registry (for example Docker images for PRs) and then we can restrict pushes to DockerHub only for Docker images that we've agreed they need to be there.

**Comment by tleopold** [comment]
@dsotirakis Do you have an update on this?

**Comment by dsotirakis** [comment]
@tleopold not really, it's up for grabs. should be really easy. you want me to work on it?

**Comment by Elfo404** [comment]
The issue mentions skipping logging in in case the actions runs on a non-push event, however the linked discussion mentions this

> Hm, I think if we agree that DockerHub will be only used for "prod" images then we can simply fail early if the event is not a push.

and in the description of this issue:
>  it'll be better if we fail safe in case there's no push event from GitHub, when this action is called

which means not running anything at all, which in turn also means not building the images, which i think it's something that users may want to do (probably as a way to test that building images work even when not "releasing").

What do we actually need to do here?

1. skip login if the event is not a push event, still perform all the building, and force `push: false`, even when explicitly set to true in
```yaml
    - name: Build and push Docker image
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
      with:
        #...
        push: ${{ inputs.push }}
        #...
```
2. skip login if the event is not a push event, still perform all the building, and fail if the `push` input is set to `true`? (basically like the previous but without mutating users' inputs, which should result in less confusion in case it happens)
3. fail if the event is not a push event and stop the whole workflow?

**Comment by dsotirakis** [comment]
I would say use your best judgment but your point here is valid:
> which means not running anything at all, which in turn also means not building the images, which i think it's something that users may want to do (probably as a way to test that building images work even when not "releasing").

so maybe solution #1?
