### ISSUE TITLE
`trigger-argo-workflow` resubmits the workflow multiple times after the workflow failure when `--wait` flag is used

### ISSUE THREAD

**Issue by fornfrey** [grafana/shared-workflows#69]
When submitting a workflow with `--wait` flag, the process blocks until the workflow is completed. However, when the submitted workflow fails the action treats it as a transient error and attempts to resubmit it. This causes multiple `AlreadyExists` errors to be printed to the job output.

This does not impact the workflow submission or execution (the workflow failed anyway) but makes the debugging process confusing. Sample output of a failed job:
```
Notice: running command
  time: "2024-03-21T09:49:12.896Z"
  level: INFO
  extraArgs:
  - --wait
Error: failed to run command, retrying
  time: "2024-03-21T10:00:05.717Z"
  level: ERROR
  error: exit status 1
  retry_in: 559.753636ms
time="2024-03-21T10:00:06.993Z" level=fatal msg="Failed to submit workflow: rpc error: code = AlreadyExists desc = workflows.argoproj.io \"my-workflow-1\" already exists, the server was not able to generate a unique name for the object"
Error: failed to run command, retrying
  time: "2024-03-21T10:00:06.995Z"
  level: ERROR
  error: exit status 1
  retry_in: 1.077149047s
time="2024-03-21T10:00:08.773Z" level=fatal msg="Failed to submit workflow: rpc error: code = AlreadyExists desc = workflows.argoproj.io \"my-workflow-1\" already exists, the server was not able to generate a unique name for the object"
```

**Comment by dblinkhorn** [comment]
newbie question...is the workflow uri returned by the argo CLI prior to completion when using the `--wait` flag?

**Comment by fornfrey** [comment]
@dblinkhorn, no, it does not. There is an issue for that too: https://github.com/grafana/shared-workflows/issues/70 
Thanks for addressing this one btw 🙇

**Comment by dblinkhorn** [comment]
@fornfrey oops i posted that comment in the wrong issue! my bad. it was meant for #70. will repost!
